In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
ann = pd.read_csv("../data/processed/mhs_main_experiment_annotations_with_split.csv")

print("Annotation rows:", ann.shape)
print("Unique comments:", ann["comment_id"].nunique())

Annotation rows: (49433, 53)
Unique comments: 19761

In [3]:
LABELS = [0, 1, 2]
label_cols = [f"hatespeech_{label}_prob" for label in LABELS]

def make_distribution(group):
    counts = group["hatespeech"].value_counts(normalize=True)
    return np.array([counts.get(label, 0.0) for label in LABELS])

def entropy_np(probs):
    probs = np.array(probs)
    probs = probs[probs > 0]
    if len(probs) == 0:
        return 0.0
    return -np.sum(probs * np.log2(probs))

In [4]:
rows = []

for comment_id, group in ann.groupby("comment_id"):
    dist = make_distribution(group)
    ent = entropy_np(dist)

    rows.append({
        "comment_id": comment_id,
        "split": group["split"].iloc[0],
        "text_clean": group["text_clean"].iloc[0],
        "annotation_count": len(group),
        "hatespeech_0_prob": dist[0],
        "hatespeech_1_prob": dist[1],
        "hatespeech_2_prob": dist[2],
        "hatespeech_entropy": ent,
        "majority_label": int(np.argmax(dist)),
        "distribution_pattern": tuple(np.round(dist, 3)),
        "is_zero_entropy": ent == 0
    })

dist_audit_df = pd.DataFrame(rows)

print(dist_audit_df.shape)
dist_audit_df.head()

(19761, 11)

,comment_id,split,text_clean,annotation_count,hatespeech_0_prob,hatespeech_1_prob,hatespeech_2_prob,hatespeech_entropy,majority_label,distribution_pattern,is_zero_entropy
0,6,train,First off you look cool as fuck! Anyway if we ...,2,1.000000,0.0,0.000000,-0.000000,0,"(1.0, 0.0, 0.0)",True
1,7,test,\*points to posters asking for palestinian rig...,2,0.500000,0.0,0.500000,1.000000,0,"(0.5, 0.0, 0.5)",False
2,10,train,"They'll come back in your plan, also. Plus we ...",3,0.333333,0.0,0.666667,0.918296,2,"(0.333, 0.0, 0.667)",False
3,11,validation,"eat my fuck, bitch",2,0.000000,0.5,0.500000,1.000000,1,"(0.0, 0.5, 0.5)",False
4,12,train,She ugly anyways,2,0.500000,0.0,0.500000,1.000000,0,"(0.5, 0.0, 0.5)",False

In [5]:
pattern_summary = (
    dist_audit_df["distribution_pattern"]
    .value_counts()
    .reset_index()
)

pattern_summary.columns = ["distribution_pattern", "comments"]
pattern_summary["percent"] = (
    pattern_summary["comments"] / len(dist_audit_df) * 100
).round(2)

pattern_summary.head(30)

     distribution_pattern  comments  percent
0         (1.0, 0.0, 0.0)     11082    56.08
1         (0.0, 0.0, 1.0)      3366    17.03
2         (0.5, 0.0, 0.5)      1325     6.71
3         (0.0, 1.0, 0.0)       858     4.34
4         (0.5, 0.5, 0.0)       598     3.03
5     (0.667, 0.0, 0.333)       569     2.88
6     (0.333, 0.0, 0.667)       412     2.08
7         (0.0, 0.5, 0.5)       296     1.50
8     (0.667, 0.333, 0.0)       287     1.45
9   (0.333, 0.333, 0.333)       205     1.04
10      (0.75, 0.0, 0.25)       149     0.75
11    (0.0, 0.333, 0.667)       110     0.56
12      (0.75, 0.25, 0.0)        94     0.48
13      (0.25, 0.0, 0.75)        88     0.45
14      (0.5, 0.25, 0.25)        77     0.39
15      (0.25, 0.25, 0.5)        61     0.31
16    (0.333, 0.667, 0.0)        45     0.23
17      (0.0, 0.25, 0.75)        32     0.16
18    (0.0, 0.667, 0.333)        23     0.12
19      (0.25, 0.5, 0.25)        11     0.06
20        (0.4, 0.0, 0.6)         3     0.02
21        (0.8, 0.2, 0.0)         3     0.02
22      (0.25, 0.75, 0.0)         3     0.02
23        (0.2, 0.2, 0.6)         2     0.01
24        (0.6, 0.2, 0.2)         2     0.01
25        (0.4, 0.2, 0.4)         2     0.01
26        (0.2, 0.0, 0.8)         2     0.01
27   (0.36, 0.095, 0.545)         1     0.01
28  (0.842, 0.105, 0.053)         1     0.01
29   (0.947, 0.03, 0.023)         1     0.01

In [6]:
unique_pattern_summary = pd.DataFrame([
    {
        "subset": "all_comments",
        "comments": len(dist_audit_df),
        "unique_patterns": dist_audit_df["distribution_pattern"].nunique(),
        "top_pattern_percent": pattern_summary.iloc[0]["percent"],
        "top_5_patterns_percent": pattern_summary.head(5)["percent"].sum(),
        "top_10_patterns_percent": pattern_summary.head(10)["percent"].sum(),
    }
])

unique_pattern_summary

,subset,comments,unique_patterns,top_pattern_percent,top_5_patterns_percent,top_10_patterns_percent
0,all_comments,19761,83,56.08,87.19,96.14

In [7]:
threshold_rows = []

for threshold in [1, 2, 3, 4, 5]:
    subset = dist_audit_df[
        dist_audit_df["annotation_count"] >= threshold
    ].copy()

    pattern_counts = subset["distribution_pattern"].value_counts()

    threshold_rows.append({
        "annotation_threshold": f">={threshold}",
        "comments": len(subset),
        "percent_of_all": round(len(subset) / len(dist_audit_df) * 100, 2),
        "unique_patterns": subset["distribution_pattern"].nunique(),
        "zero_entropy_percent": round((subset["hatespeech_entropy"] == 0).mean() * 100, 2),
        "mean_entropy": subset["hatespeech_entropy"].mean(),
        "median_entropy": subset["hatespeech_entropy"].median(),
        "top_pattern": pattern_counts.index[0] if len(pattern_counts) > 0 else None,
        "top_pattern_percent": round(pattern_counts.iloc[0] / len(subset) * 100, 2) if len(subset) > 0 else None,
        "top_5_patterns_percent": round(pattern_counts.head(5).sum() / len(subset) * 100, 2) if len(subset) > 0 else None,
        "top_10_patterns_percent": round(pattern_counts.head(10).sum() / len(subset) * 100, 2) if len(subset) > 0 else None,
    })

threshold_pattern_summary = pd.DataFrame(threshold_rows)
threshold_pattern_summary

,annotation_threshold,comments,percent_of_all,unique_patterns,zero_entropy_percent,mean_entropy,median_entropy,top_pattern,top_pattern_percent,top_5_patterns_percent,top_10_patterns_percent
0,>=1,19761,100.00,83,77.46,0.225016,0.000000,"(1.0, 0.0, 0.0)",56.08,87.19,96.14
1,>=2,10639,53.84,83,58.13,0.417948,0.000000,"(1.0, 0.0, 0.0)",47.98,80.89,93.57
2,>=3,4644,23.50,83,49.35,0.504641,0.721928,"(1.0, 0.0, 0.0)",43.07,76.59,90.65
3,>=4,1235,6.25,75,43.24,0.559334,0.811278,"(1.0, 0.0, 0.0)",38.38,72.87,93.04
4,>=5,87,0.44,63,20.69,0.615387,0.677404,"(1.0, 0.0, 0.0)",17.24,29.89,39.08

In [8]:
split_threshold_rows = []

for split in ["train", "validation", "test"]:
    split_df = dist_audit_df[dist_audit_df["split"] == split]

    for threshold in [1, 2, 3]:
        subset = split_df[split_df["annotation_count"] >= threshold]

        pattern_counts = subset["distribution_pattern"].value_counts()

        split_threshold_rows.append({
            "split": split,
            "annotation_threshold": f">={threshold}",
            "comments": len(subset),
            "unique_patterns": subset["distribution_pattern"].nunique(),
            "zero_entropy_percent": round((subset["hatespeech_entropy"] == 0).mean() * 100, 2),
            "mean_entropy": subset["hatespeech_entropy"].mean(),
            "top_pattern_percent": round(pattern_counts.iloc[0] / len(subset) * 100, 2) if len(subset) > 0 else None,
            "top_5_patterns_percent": round(pattern_counts.head(5).sum() / len(subset) * 100, 2) if len(subset) > 0 else None
        })

split_threshold_pattern_summary = pd.DataFrame(split_threshold_rows)
split_threshold_pattern_summary

,split,annotation_threshold,comments,unique_patterns,zero_entropy_percent,mean_entropy,top_pattern_percent,top_5_patterns_percent
0,train,>=1,13832,68,77.56,0.223532,56.28,87.23
1,train,>=2,7437,68,58.26,0.415744,48.20,81.05
2,train,>=3,3252,68,49.63,0.499966,43.33,76.97
3,validation,>=1,2964,29,77.13,0.228493,56.17,87.11
4,validation,>=2,1601,29,57.65,0.423018,47.53,80.76
5,validation,>=3,687,29,49.49,0.504006,43.96,75.98
6,test,>=1,2965,29,77.30,0.228469,55.04,87.05
7,test,>=2,1601,29,57.96,0.423117,47.41,80.26
8,test,>=3,705,27,47.94,0.526824,40.99,75.46

In [9]:
nonzero_df = dist_audit_df[dist_audit_df["hatespeech_entropy"] > 0].copy()

nonzero_pattern_counts = (
    nonzero_df["distribution_pattern"]
    .value_counts()
    .reset_index()
)

nonzero_pattern_counts.columns = ["distribution_pattern", "comments"]
nonzero_pattern_counts["percent"] = (
    nonzero_pattern_counts["comments"] / len(nonzero_df) * 100
).round(2)

print("Non-zero entropy comments:", len(nonzero_df))
print("Percent of all:", round(len(nonzero_df) / len(dist_audit_df) * 100, 2))
print("Unique patterns:", nonzero_df["distribution_pattern"].nunique())

nonzero_pattern_counts.head(30)

Non-zero entropy comments: 4455
Percent of all: 22.54
Unique patterns: 80

     distribution_pattern  comments  percent
0         (0.5, 0.0, 0.5)      1325    29.74
1         (0.5, 0.5, 0.0)       598    13.42
2     (0.667, 0.0, 0.333)       569    12.77
3     (0.333, 0.0, 0.667)       412     9.25
4         (0.0, 0.5, 0.5)       296     6.64
5     (0.667, 0.333, 0.0)       287     6.44
6   (0.333, 0.333, 0.333)       205     4.60
7       (0.75, 0.0, 0.25)       149     3.34
8     (0.0, 0.333, 0.667)       110     2.47
9       (0.75, 0.25, 0.0)        94     2.11
10      (0.25, 0.0, 0.75)        88     1.98
11      (0.5, 0.25, 0.25)        77     1.73
12      (0.25, 0.25, 0.5)        61     1.37
13    (0.333, 0.667, 0.0)        45     1.01
14      (0.0, 0.25, 0.75)        32     0.72
15    (0.0, 0.667, 0.333)        23     0.52
16      (0.25, 0.5, 0.25)        11     0.25
17        (0.4, 0.0, 0.6)         3     0.07
18        (0.8, 0.2, 0.0)         3     0.07
19      (0.25, 0.75, 0.0)         3     0.07
20        (0.2, 0.2, 0.6)         2     0.04
21        (0.4, 0.2, 0.4)         2     0.04
22        (0.6, 0.2, 0.2)         2     0.04
23        (0.2, 0.0, 0.8)         2     0.04
24        (0.6, 0.4, 0.0)         1     0.02
25  (0.842, 0.105, 0.053)         1     0.02
26   (0.947, 0.03, 0.023)         1     0.02
27  (0.579, 0.053, 0.368)         1     0.02
28  (0.941, 0.028, 0.031)         1     0.02
29      (0.05, 0.0, 0.95)         1     0.02

In [10]:
nonzero_threshold_rows = []

for threshold in [2, 3, 4, 5]:
    subset = dist_audit_df[
        (dist_audit_df["annotation_count"] >= threshold) &
        (dist_audit_df["hatespeech_entropy"] > 0)
    ].copy()

    pattern_counts = subset["distribution_pattern"].value_counts()

    nonzero_threshold_rows.append({
        "subset": f"nonzero_entropy_and_annotations>={threshold}",
        "comments": len(subset),
        "percent_of_all": round(len(subset) / len(dist_audit_df) * 100, 2),
        "unique_patterns": subset["distribution_pattern"].nunique(),
        "mean_entropy": subset["hatespeech_entropy"].mean(),
        "median_entropy": subset["hatespeech_entropy"].median(),
        "top_pattern_percent": round(pattern_counts.iloc[0] / len(subset) * 100, 2) if len(subset) > 0 else None,
        "top_5_patterns_percent": round(pattern_counts.head(5).sum() / len(subset) * 100, 2) if len(subset) > 0 else None,
        "top_10_patterns_percent": round(pattern_counts.head(10).sum() / len(subset) * 100, 2) if len(subset) > 0 else None,
    })

nonzero_threshold_summary = pd.DataFrame(nonzero_threshold_rows)
nonzero_threshold_summary

,subset,comments,percent_of_all,unique_patterns,mean_entropy,median_entropy,top_pattern_percent,top_5_patterns_percent,top_10_patterns_percent
0,nonzero_entropy_and_annotations>=2,4455,22.54,80,0.998103,1.000000,29.74,71.83,90.80
1,nonzero_entropy_and_annotations>=3,2352,11.90,80,0.996408,0.918296,24.19,68.96,88.69
2,nonzero_entropy_and_annotations>=4,701,3.55,73,0.985418,0.811278,21.26,71.75,89.73
3,nonzero_entropy_and_annotations>=5,69,0.35,61,0.775923,0.774243,4.35,17.39,26.09

In [11]:
subset_defs = {
    "all_comments": dist_audit_df,
    "annotations>=2": dist_audit_df[dist_audit_df["annotation_count"] >= 2],
    "annotations>=3": dist_audit_df[dist_audit_df["annotation_count"] >= 3],
    "nonzero_entropy": dist_audit_df[dist_audit_df["hatespeech_entropy"] > 0],
    "nonzero_entropy_and_annotations>=2": dist_audit_df[
        (dist_audit_df["hatespeech_entropy"] > 0) &
        (dist_audit_df["annotation_count"] >= 2)
    ],
    "nonzero_entropy_and_annotations>=3": dist_audit_df[
        (dist_audit_df["hatespeech_entropy"] > 0) &
        (dist_audit_df["annotation_count"] >= 3)
    ],
}

majority_rows = []

for subset_name, subset in subset_defs.items():
    counts = subset["majority_label"].value_counts(normalize=True)

    majority_rows.append({
        "subset": subset_name,
        "comments": len(subset),
        "majority_0_percent": round(counts.get(0, 0) * 100, 2),
        "majority_1_percent": round(counts.get(1, 0) * 100, 2),
        "majority_2_percent": round(counts.get(2, 0) * 100, 2),
    })

majority_subset_summary = pd.DataFrame(majority_rows)
majority_subset_summary

,subset,comments,majority_0_percent,majority_1_percent,majority_2_percent
0,all_comments,19761,72.95,6.26,20.79
1,annotations>=2,10639,79.32,4.22,16.46
2,annotations>=3,4644,75.90,1.89,22.20
3,nonzero_entropy,4455,74.84,8.51,16.66
4,nonzero_entropy_and_annotations>=2,4455,74.84,8.51,16.66
5,nonzero_entropy_and_annotations>=3,2352,64.84,3.61,31.55

In [12]:
dist_audit_df["pattern_type"] = np.where(
    dist_audit_df["hatespeech_entropy"] == 0,
    "one_hot_consensus",
    "mixed_distribution"
)

pattern_type_summary = (
    dist_audit_df
    .groupby("pattern_type")
    .agg(
        comments=("comment_id", "count"),
        mean_annotation_count=("annotation_count", "mean"),
        median_annotation_count=("annotation_count", "median"),
        mean_entropy=("hatespeech_entropy", "mean"),
        majority_0_percent=("majority_label", lambda x: round((x == 0).mean() * 100, 2)),
        majority_1_percent=("majority_label", lambda x: round((x == 1).mean() * 100, 2)),
        majority_2_percent=("majority_label", lambda x: round((x == 2).mean() * 100, 2)),
    )
    .reset_index()
)

pattern_type_summary

,pattern_type,comments,mean_annotation_count,median_annotation_count,mean_entropy,majority_0_percent,majority_1_percent,majority_2_percent
0,mixed_distribution,4455,5.593490,3.0,0.998103,74.84,8.51,16.66
1,one_hot_consensus,15306,1.601594,1.0,0.000000,72.40,5.61,21.99

In [13]:
common_mixed_patterns = (
    dist_audit_df[dist_audit_df["hatespeech_entropy"] > 0]
    ["distribution_pattern"]
    .value_counts()
    .head(10)
    .index
)

example_rows = []

for pattern in common_mixed_patterns:
    examples = dist_audit_df[
        dist_audit_df["distribution_pattern"] == pattern
    ].head(3)

    for _, row in examples.iterrows():
        example_rows.append({
            "distribution_pattern": pattern,
            "comment_id": row["comment_id"],
            "split": row["split"],
            "annotation_count": row["annotation_count"],
            "entropy": row["hatespeech_entropy"],
            "majority_label": row["majority_label"],
            "text_clean": row["text_clean"][:300]
        })

mixed_pattern_examples = pd.DataFrame(example_rows)
mixed_pattern_examples

,distribution_pattern,comment_id,split,annotation_count,entropy,majority_label,text_clean
0,"(0.5, 0.0, 0.5)",7,test,2,1.000000,0,\*points to posters asking for palestinian rig...
1,"(0.5, 0.0, 0.5)",12,train,2,1.000000,0,She ugly anyways
2,"(0.5, 0.0, 0.5)",22,train,2,1.000000,0,The guys are one thing but then you have a wom...
3,"(0.5, 0.5, 0.0)",88,train,2,1.000000,0,Better get 2 abortions for your spawn cause yo...
4,"(0.5, 0.5, 0.0)",186,train,2,1.000000,0,Um if a penis is triggering the deeper fears o...
5,"(0.5, 0.5, 0.0)",202,validation,2,1.000000,0,More conflation of sex and gender.. I. Am. Sho...
6,"(0.667, 0.0, 0.333)",26,train,3,0.918296,0,I'd love to rip those panties off and shove my...
7,"(0.667, 0.0, 0.333)",132,validation,3,0.918296,0,"As someone from the US, fuck our craven sack o..."
8,"(0.667, 0.0, 0.333)",224,train,3,0.918296,0,I fought so my daughters could be sluts!
9,"(0.333, 0.0, 0.667)",10,train,3,0.918296,2,"They'll come back in your plan, also. Plus we ..."
10,"(0.333, 0.0, 0.667)",268,train,3,0.918296,2,Fuck those Saudi rats
11,"(0.333, 0.0, 0.667)",450,train,3,0.918296,2,Chivalry is for cucks Maybe in a day and age w...
12,"(0.0, 0.5, 0.5)",11,validation,2,1.000000,1,"eat my fuck, bitch"
13,"(0.0, 0.5, 0.5)",161,train,2,1.000000,1,They are..... Freaking sluts and baby murderin...
14,"(0.0, 0.5, 0.5)",230,train,2,1.000000,1,I wish I could be in that room as they take tu...
15,"(0.667, 0.333, 0.0)",29,train,3,0.918296,0,I'm absolutely for equal rights for all people...
16,"(0.667, 0.333, 0.0)",38,train,3,0.918296,0,"Give me your tired, your poor, your religious ..."
17,"(0.667, 0.333, 0.0)",140,train,3,0.918296,0,"true, she probably will get a slap on the hand..."
18,"(0.333, 0.333, 0.333)",550,validation,3,1.584963,0,That bitch epitomizes trash
19,"(0.333, 0.333, 0.333)",724,train,3,1.584963,0,I wont believe she really is a woke feminist u...
20,"(0.333, 0.333, 0.333)",1006,train,3,1.584963,0,"Worthless whore, these tits with look nice wit..."
21,"(0.75, 0.0, 0.25)",260,validation,4,0.811278,0,Send the fuckers back across the border
22,"(0.75, 0.0, 0.25)",625,test,4,0.811278,0,Anti-feminists: most women don't belong in he ...
23,"(0.75, 0.0, 0.25)",737,train,4,0.811278,0,She's disgusting. I'd let her suck my cock.
24,"(0.0, 0.333, 0.667)",854,test,3,0.918296,2,Wtf is wrong with you cunt bag? Did mommy not ...
25,"(0.0, 0.333, 0.667)",902,test,3,0.918296,2,She was a whore who craved multiple cocks in h...
26,"(0.0, 0.333, 0.667)",1530,train,3,0.918296,2,I'd dump a load in you and then dry my dirty c...
27,"(0.75, 0.25, 0.0)",119,train,4,0.811278,0,You know how women put so much effort into loo...
28,"(0.75, 0.25, 0.0)",772,train,4,0.811278,0,Swedes are always trying to steal stuff. First...
29,"(0.75, 0.25, 0.0)",823,train,4,0.811278,0,there really is some weird implied sense in wo...

In [15]:
os.makedirs("../results/tables", exist_ok=True)

report_path = "../results/tables/hatespeech_distribution_pattern_audit.txt"

with open(report_path, "w", encoding="utf-8") as f:
    f.write("HATESPEECH DISTRIBUTION PATTERN AUDIT\n")
    f.write("=" * 90 + "\n\n")

    f.write("1. DATASET SIZE\n")
    f.write("-" * 90 + "\n")
    f.write(f"Unique comments: {len(dist_audit_df)}\n")
    f.write(f"Annotation rows: {len(ann)}\n\n")

    f.write("2. OVERALL MOST COMMON DISTRIBUTION PATTERNS\n")
    f.write("-" * 90 + "\n")
    f.write(pattern_summary.head(30).to_string(index=False))
    f.write("\n\n")

    f.write("3. UNIQUE PATTERN SUMMARY\n")
    f.write("-" * 90 + "\n")
    f.write(unique_pattern_summary.to_string(index=False))
    f.write("\n\n")

    f.write("4. PATTERN SUMMARY BY ANNOTATION THRESHOLD\n")
    f.write("-" * 90 + "\n")
    f.write(threshold_pattern_summary.to_string(index=False))
    f.write("\n\n")

    f.write("5. PATTERN SUMMARY BY SPLIT AND THRESHOLD\n")
    f.write("-" * 90 + "\n")
    f.write(split_threshold_pattern_summary.to_string(index=False))
    f.write("\n\n")

    f.write("6. NON-ZERO ENTROPY PATTERNS\n")
    f.write("-" * 90 + "\n")
    f.write(nonzero_pattern_counts.head(30).to_string(index=False))
    f.write("\n\n")

    f.write("7. NON-ZERO ENTROPY + ANNOTATION THRESHOLD SUMMARY\n")
    f.write("-" * 90 + "\n")
    f.write(nonzero_threshold_summary.to_string(index=False))
    f.write("\n\n")

    f.write("8. MAJORITY LABEL DISTRIBUTION BY SUBSET\n")
    f.write("-" * 90 + "\n")
    f.write(majority_subset_summary.to_string(index=False))
    f.write("\n\n")

    f.write("9. PATTERN TYPE SUMMARY\n")
    f.write("-" * 90 + "\n")
    f.write(pattern_type_summary.to_string(index=False))
    f.write("\n\n")

    f.write("10. COMMON MIXED PATTERN EXAMPLES\n")
    f.write("-" * 90 + "\n")
    f.write(mixed_pattern_examples.to_string(index=False))
    f.write("\n\n")


print("Saved:", report_path)
print(open(report_path, encoding="utf-8").read())

Saved: ../results/tables/hatespeech_distribution_pattern_audit.txt
HATESPEECH DISTRIBUTION PATTERN AUDIT
==========================================================================================

1. DATASET SIZE
------------------------------------------------------------------------------------------
Unique comments: 19761
Annotation rows: 49433

2. OVERALL MOST COMMON DISTRIBUTION PATTERNS
------------------------------------------------------------------------------------------
 distribution_pattern  comments  percent
      (1.0, 0.0, 0.0)     11082    56.08
      (0.0, 0.0, 1.0)      3366    17.03
      (0.5, 0.0, 0.5)      1325     6.71
      (0.0, 1.0, 0.0)       858     4.34
      (0.5, 0.5, 0.0)       598     3.03
  (0.667, 0.0, 0.333)       569     2.88
  (0.333, 0.0, 0.667)       412     2.08
      (0.0, 0.5, 0.5)       296     1.50
  (0.667, 0.333, 0.0)       287     1.45
(0.333, 0.333, 0.333)       205     1.04
    (0.75, 0.0, 0.25)       149     0.75
  (0.0, 0.333, 0.667)       110     0.56
    (0.75, 0.25, 0.0)        94     0.48
    (0.25, 0.0, 0.75)        88     0.45
    (0.5, 0.25, 0.25)        77     0.39
    (0.25, 0.25, 0.5)        61     0.31
  (0.333, 0.667, 0.0)        45     0.23
    (0.0, 0.25, 0.75)        32     0.16
  (0.0, 0.667, 0.333)        23     0.12
    (0.25, 0.5, 0.25)        11     0.06
      (0.4, 0.0, 0.6)         3     0.02
      (0.8, 0.2, 0.0)         3     0.02
    (0.25, 0.75, 0.0)         3     0.02
      (0.2, 0.2, 0.6)         2     0.01
      (0.6, 0.2, 0.2)         2     0.01
      (0.4, 0.2, 0.4)         2     0.01
      (0.2, 0.0, 0.8)         2     0.01
 (0.36, 0.095, 0.545)         1     0.01
(0.842, 0.105, 0.053)         1     0.01
 (0.947, 0.03, 0.023)         1     0.01

3. UNIQUE PATTERN SUMMARY
------------------------------------------------------------------------------------------
      subset  comments  unique_patterns  top_pattern_percent  top_5_patterns_percent  top_10_patterns_percent
all_comments     19761               83                56.08                   87.19                    96.14

4. PATTERN SUMMARY BY ANNOTATION THRESHOLD
------------------------------------------------------------------------------------------
annotation_threshold  comments  percent_of_all  unique_patterns  zero_entropy_percent  mean_entropy  median_entropy     top_pattern  top_pattern_percent  top_5_patterns_percent  top_10_patterns_percent
                 >=1     19761          100.00               83                 77.46      0.225016        0.000000 (1.0, 0.0, 0.0)                56.08                   87.19                    96.14
                 >=2     10639           53.84               83                 58.13      0.417948        0.000000 (1.0, 0.0, 0.0)                47.98                   80.89                    93.57
                 >=3      4644           23.50               83                 49.35      0.504641        0.721928 (1.0, 0.0, 0.0)                43.07                   76.59                    90.65
                 >=4      1235            6.25               75                 43.24      0.559334        0.811278 (1.0, 0.0, 0.0)                38.38                   72.87                    93.04
                 >=5        87            0.44               63                 20.69      0.615387        0.677404 (1.0, 0.0, 0.0)                17.24                   29.89                    39.08

5. PATTERN SUMMARY BY SPLIT AND THRESHOLD
------------------------------------------------------------------------------------------
     split annotation_threshold  comments  unique_patterns  zero_entropy_percent  mean_entropy  top_pattern_percent  top_5_patterns_percent
     train                  >=1     13832               68                 77.56      0.223532                56.28                   87.23
     train                  >=2      7437               68                 58.26      0.415744                48.20                   81.05
     train                  >=3      3252               68                 49.63      0.499966                43.33                   76.97
validation                  >=1      2964               29                 77.13      0.228493                56.17                   87.11
validation                  >=2      1601               29                 57.65      0.423018                47.53                   80.76
validation                  >=3       687               29                 49.49      0.504006                43.96                   75.98
      test                  >=1      2965               29                 77.30      0.228469                55.04                   87.05
      test                  >=2      1601               29                 57.96      0.423117                47.41                   80.26
      test                  >=3       705               27                 47.94      0.526824                40.99                   75.46

6. NON-ZERO ENTROPY PATTERNS
------------------------------------------------------------------------------------------
 distribution_pattern  comments  percent
      (0.5, 0.0, 0.5)      1325    29.74
      (0.5, 0.5, 0.0)       598    13.42
  (0.667, 0.0, 0.333)       569    12.77
  (0.333, 0.0, 0.667)       412     9.25
      (0.0, 0.5, 0.5)       296     6.64
  (0.667, 0.333, 0.0)       287     6.44
(0.333, 0.333, 0.333)       205     4.60
    (0.75, 0.0, 0.25)       149     3.34
  (0.0, 0.333, 0.667)       110     2.47
    (0.75, 0.25, 0.0)        94     2.11
    (0.25, 0.0, 0.75)        88     1.98
    (0.5, 0.25, 0.25)        77     1.73
    (0.25, 0.25, 0.5)        61     1.37
  (0.333, 0.667, 0.0)        45     1.01
    (0.0, 0.25, 0.75)        32     0.72
  (0.0, 0.667, 0.333)        23     0.52
    (0.25, 0.5, 0.25)        11     0.25
      (0.4, 0.0, 0.6)         3     0.07
      (0.8, 0.2, 0.0)         3     0.07
    (0.25, 0.75, 0.0)         3     0.07
      (0.2, 0.2, 0.6)         2     0.04
      (0.4, 0.2, 0.4)         2     0.04
      (0.6, 0.2, 0.2)         2     0.04
      (0.2, 0.0, 0.8)         2     0.04
      (0.6, 0.4, 0.0)         1     0.02
(0.842, 0.105, 0.053)         1     0.02
 (0.947, 0.03, 0.023)         1     0.02
(0.579, 0.053, 0.368)         1     0.02
(0.941, 0.028, 0.031)         1     0.02
    (0.05, 0.0, 0.95)         1     0.02

7. NON-ZERO ENTROPY + ANNOTATION THRESHOLD SUMMARY
------------------------------------------------------------------------------------------
                            subset  comments  percent_of_all  unique_patterns  mean_entropy  median_entropy  top_pattern_percent  top_5_patterns_percent  top_10_patterns_percent
nonzero_entropy_and_annotations>=2      4455           22.54               80      0.998103        1.000000                29.74                   71.83                    90.80
nonzero_entropy_and_annotations>=3      2352           11.90               80      0.996408        0.918296                24.19                   68.96                    88.69
nonzero_entropy_and_annotations>=4       701            3.55               73      0.985418        0.811278                21.26                   71.75                    89.73
nonzero_entropy_and_annotations>=5        69            0.35               61      0.775923        0.774243                 4.35                   17.39                    26.09

8. MAJORITY LABEL DISTRIBUTION BY SUBSET
------------------------------------------------------------------------------------------
                            subset  comments  majority_0_percent  majority_1_percent  majority_2_percent
                      all_comments     19761               72.95                6.26               20.79
                    annotations>=2     10639               79.32                4.22               16.46
                    annotations>=3      4644               75.90                1.89               22.20
                   nonzero_entropy      4455               74.84                8.51               16.66
nonzero_entropy_and_annotations>=2      4455               74.84                8.51               16.66
nonzero_entropy_and_annotations>=3      2352               64.84                3.61               31.55

9. PATTERN TYPE SUMMARY
------------------------------------------------------------------------------------------
      pattern_type  comments  mean_annotation_count  median_annotation_count  mean_entropy  majority_0_percent  majority_1_percent  majority_2_percent
mixed_distribution      4455               5.593490                      3.0      0.998103               74.84                8.51               16.66
 one_hot_consensus     15306               1.601594                      1.0      0.000000               72.40                5.61               21.99

10. COMMON MIXED PATTERN EXAMPLES
------------------------------------------------------------------------------------------
 distribution_pattern  comment_id      split  annotation_count  entropy  majority_label                                                                                                                                                                                                                                                                                                   text_clean
      (0.5, 0.0, 0.5)           7       test                 2 1.000000               0                                                 \*points to posters asking for palestinian rights and freedom\* theyre antisemetic and want to kill all the jews and dont acknowledge our right to exist ​ cant wait for this prick to die and go straight to hell. ill dig him the hole to get there myself
      (0.5, 0.0, 0.5)          12      train                 2 1.000000               0                                                                                                                                                                                                                                                                                             She ugly anyways
      (0.5, 0.0, 0.5)          22      train                 2 1.000000               0                                                                                                                                                             The guys are one thing but then you have a woman there making one of the worst comments. I say rape them all with a cactus and say God willed it
      (0.5, 0.5, 0.0)          88      train                 2 1.000000               0                                                                                                                                                                                                                                                  Better get 2 abortions for your spawn cause you're a dickun
      (0.5, 0.5, 0.0)         186      train                 2 1.000000               0                                                                                                                                                                                                                Um if a penis is triggering the deeper fears of the human mind, probably penis isn't for you.
      (0.5, 0.5, 0.0)         202 validation                 2 1.000000               0 More conflation of sex and gender.. I. Am. Shocked 🙄 I, a GNC, child free woman, am a survivor of rape who's had a rape kit exam (which includes a swipe of my cervix) AND given Plan B, why? Because unlike you, I AM FEMALE, and those services were created (and fought for) specifically to combat the s
  (0.667, 0.0, 0.333)          26      train                 3 0.918296               0                                                                                                                                                                                                                                          I'd love to rip those panties off and shove my fat cock in her ass.
  (0.667, 0.0, 0.333)         132 validation                 3 0.918296               0 As someone from the US, fuck our craven sack of shit politicians and our rape-enabling state governments. We have no fucking right to act like we're superior to anyone when we've completely regressed to the same type of pre-1970s policies that led to the deaths of thousands of women. Anyone who beli
  (0.667, 0.0, 0.333)         224      train                 3 0.918296               0                                                                                                                                                                                                                                                                     I fought so my daughters could be sluts!
  (0.333, 0.0, 0.667)          10      train                 3 0.918296               2                            They'll come back in your plan, also. Plus we pay to jail them for 2 years. With my plan, we jail them after they come back. And deport them again. It really doesn't matter either way until we're build the wall, and shoot the invaders as enemies when they cross the border.
  (0.333, 0.0, 0.667)         268      train                 3 0.918296               2                                                                                                                                                                                                                                                                                        Fuck those Saudi rats
  (0.333, 0.0, 0.667)         450      train                 3 0.918296               2                                    Chivalry is for cucks Maybe in a day and age where you got something for it But women are addled with feminist entitlement, slutiness, victim complex, and a complete lack of gratitude No chivalry for these little miss independents. Why the fuck would anyone bother?
      (0.0, 0.5, 0.5)          11 validation                 2 1.000000               1                                                                                                                                                                                                                                                                                           eat my fuck, bitch
      (0.0, 0.5, 0.5)         161      train                 2 1.000000               1                                                                                                                                                                                                                                                 They are..... Freaking sluts and baby murdering slut fuckers
      (0.0, 0.5, 0.5)         230      train                 2 1.000000               1                                                                                                             I wish I could be in that room as they take turns pumping her full of their superior seed. And I could just see them laughing at me as I spill my pitiful cum to watching the future of my race.
  (0.667, 0.333, 0.0)          29      train                 3 0.918296               0                                                       I'm absolutely for equal rights for all people. In my life, things generally do seem equal, so I think it's more important at this point to focus on places where there is currently horrible gender inequality (probably the Middle East and Africa).
  (0.667, 0.333, 0.0)          38      train                 3 0.918296               0                                                                                              Give me your tired, your poor, your religious nutcases, your criminals ... the wretched refuse of your teeming shore ... and finally allow Europe to be subjected to the moronic whims of this wretched refuse.
  (0.667, 0.333, 0.0)         140      train                 3 0.918296               0                                                                                                                                          true, she probably will get a slap on the hand and a head nod from the simped judge and grants her the pussy pass so she can go and whine about the male privilege.
(0.333, 0.333, 0.333)         550 validation                 3 1.584963               0                                                                                                                                                                                                                                                                                  That bitch epitomizes trash
(0.333, 0.333, 0.333)         724      train                 3 1.584963               0                                                                                                                                                                                                I wont believe she really is a woke feminist until there us a midget xer behind her with xer dick in her ass.
(0.333, 0.333, 0.333)        1006      train                 3 1.584963               0                                                                                                                                                                                                                                           Worthless whore, these tits with look nice with bite marks and cum
    (0.75, 0.0, 0.25)         260 validation                 4 0.811278               0                                                                                                                                                                                                                                                                      Send the fuckers back across the border
    (0.75, 0.0, 0.25)         625       test                 4 0.811278               0                                               Anti-feminists: most women don't belong in he military because they're weak Law: doesn't require women to register for the selective service Anti-feminists: interesting you never hear feminists saying women should be drafted, what about women's equality?
    (0.75, 0.0, 0.25)         737      train                 4 0.811278               0                                                                                                                                                                                                                                                                  She's disgusting. I'd let her suck my cock.
  (0.0, 0.333, 0.667)         854       test                 3 0.918296               2                                                                                                                                                                                                                                           Wtf is wrong with you cunt bag? Did mommy not change your diapers?
  (0.0, 0.333, 0.667)         902       test                 3 0.918296               2                                                                                                                                                                                                                                     She was a whore who craved multiple cocks in her cunt. plain and simple.
  (0.0, 0.333, 0.667)        1530      train                 3 0.918296               2                                                                                                                                                                                                       I'd dump a load in you and then dry my dirty cock off with a fist full of your hair. You're a cum rag.